language: cpp
compiler: gcc
sudo: require
dist: trusty

# Workaround for: https://github.com/travis-ci/travis-ci/issues/8317
addons:
  apt:
    packages:
        - libsdl2-dev
        - libsdl2-ttf-dev
        - pkg-config
        - libjansson-dev
        - libspeex-dev
        - libspeexdsp-dev
        - libcurl4-openssl-dev
        - libcrypto++-dev
        - libfontconfig1-dev
        - libfreetype6-dev
        - libpng-dev
        - libssl-dev

install:
  - sudo add-apt-repository -y ppa:jonathonf/php7.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # Workaround for: g++: error: unrecognized command line option ‘-std=gnu++14’
  - sudo apt-get update -qq
  - sudo apt-get -y update
  - sudo apt-get -y install gcc-4.9 g++-4.9 libzip-dev # Workaround for: package 'libzip>=1.0' not found
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  
script:
  - mkdir build ; cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
  - make -j$(nproc)
  - make DESTDIR=appdir -j$(nproc) install ; find appdir/
  - wget -c -q "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - # Workaround to increase compatibility with older systems; see https://github.com/darealshinji/AppImageKit-checkrt for details
  - mkdir -p appdir/usr/optional/ ; cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ./appdir/usr/optional/
  - ( cd appdir ; rm AppRun ; wget https://github.com/darealshinji/AppImageKit-checkrt/releases/download/continuous/AppRun-patched-x86_64 -O AppRun ; chmod a+x AppRun)
  - ./linuxdeployqt*.AppImage --appimage-extract
  - ./squashfs-root/AppRun ./appdir/usr/share/applications/*.desktop -appimage

after_success:
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - # curl --upload-file ./APPNAME*.AppImage https://transfer.sh/OpenRCT2-git.$(git rev-parse --short HEAD)-x86_64.AppImage
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./OpenRCT2*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
